-- MySQL Script generated by MySQL Workbench
-- Wed Nov  8 17:34:45 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema Nosted
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Nosted
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Nosted` DEFAULT CHARACTER SET utf8mb4 ;
USE `Nosted` ;

-- -----------------------------------------------------
-- Table `Nosted`.`Adresse`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Nosted`.`Adresse` (
  `Id` INT(11) NOT NULL AUTO_INCREMENT,
  `Postkode` INT(11) NOT NULL,
  `Poststed` LONGTEXT NOT NULL,
  `Gate` LONGTEXT NOT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `Nosted`.`AspNetRoles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Nosted`.`AspNetRoles` (
  `Id` VARCHAR(255) NOT NULL,
  `Name` VARCHAR(256) NULL DEFAULT NULL,
  `NormalizedName` VARCHAR(256) NULL DEFAULT NULL,
  `ConcurrencyStamp` LONGTEXT NULL DEFAULT NULL,
  PRIMARY KEY (`Id`),
  UNIQUE INDEX `RoleNameIndex` (`NormalizedName` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `Nosted`.`AspNetRoleClaims`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Nosted`.`AspNetRoleClaims` (
  `Id` INT(11) NOT NULL AUTO_INCREMENT,
  `RoleId` VARCHAR(255) NOT NULL,
  `ClaimType` LONGTEXT NULL DEFAULT NULL,
  `ClaimValue` LONGTEXT NULL DEFAULT NULL,
  PRIMARY KEY (`Id`),
  INDEX `IX_AspNetRoleClaims_RoleId` (`RoleId` ASC) VISIBLE,
  CONSTRAINT `FK_AspNetRoleClaims_AspNetRoles_RoleId`
    FOREIGN KEY (`RoleId`)
    REFERENCES `Nosted`.`AspNetRoles` (`Id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `Nosted`.`AspNetUsers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Nosted`.`AspNetUsers` (
  `Id` VARCHAR(255) NOT NULL,
  `UserName` VARCHAR(256) NULL DEFAULT NULL,
  `NormalizedUserName` VARCHAR(256) NULL DEFAULT NULL,
  `Email` VARCHAR(256) NULL DEFAULT NULL,
  `NormalizedEmail` VARCHAR(256) NULL DEFAULT NULL,
  `EmailConfirmed` TINYINT(1) NOT NULL,
  `PasswordHash` LONGTEXT NULL DEFAULT NULL,
  `SecurityStamp` LONGTEXT NULL DEFAULT NULL,
  `ConcurrencyStamp` LONGTEXT NULL DEFAULT NULL,
  `PhoneNumber` LONGTEXT NULL DEFAULT NULL,
  `PhoneNumberConfirmed` TINYINT(1) NOT NULL,
  `TwoFactorEnabled` TINYINT(1) NOT NULL,
  `LockoutEnd` DATETIME(6) NULL DEFAULT NULL,
  `LockoutEnabled` TINYINT(1) NOT NULL,
  `AccessFailedCount` INT(11) NOT NULL,
  PRIMARY KEY (`Id`),
  UNIQUE INDEX `UserNameIndex` (`NormalizedUserName` ASC) VISIBLE,
  INDEX `EmailIndex` (`NormalizedEmail` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `Nosted`.`AspNetUserClaims`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Nosted`.`AspNetUserClaims` (
  `Id` INT(11) NOT NULL AUTO_INCREMENT,
  `UserId` VARCHAR(255) NOT NULL,
  `ClaimType` LONGTEXT NULL DEFAULT NULL,
  `ClaimValue` LONGTEXT NULL DEFAULT NULL,
  PRIMARY KEY (`Id`),
  INDEX `IX_AspNetUserClaims_UserId` (`UserId` ASC) VISIBLE,
  CONSTRAINT `FK_AspNetUserClaims_AspNetUsers_UserId`
    FOREIGN KEY (`UserId`)
    REFERENCES `Nosted`.`AspNetUsers` (`Id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `Nosted`.`AspNetUserLogins`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Nosted`.`AspNetUserLogins` (
  `LoginProvider` VARCHAR(255) NOT NULL,
  `ProviderKey` VARCHAR(255) NOT NULL,
  `ProviderDisplayName` LONGTEXT NULL DEFAULT NULL,
  `UserId` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`LoginProvider`, `ProviderKey`),
  INDEX `IX_AspNetUserLogins_UserId` (`UserId` ASC) VISIBLE,
  CONSTRAINT `FK_AspNetUserLogins_AspNetUsers_UserId`
    FOREIGN KEY (`UserId`)
    REFERENCES `Nosted`.`AspNetUsers` (`Id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `Nosted`.`AspNetUserRoles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Nosted`.`AspNetUserRoles` (
  `UserId` VARCHAR(255) NOT NULL,
  `RoleId` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`UserId`, `RoleId`),
  INDEX `IX_AspNetUserRoles_RoleId` (`RoleId` ASC) VISIBLE,
  CONSTRAINT `FK_AspNetUserRoles_AspNetRoles_RoleId`
    FOREIGN KEY (`RoleId`)
    REFERENCES `Nosted`.`AspNetRoles` (`Id`)
    ON DELETE CASCADE,
  CONSTRAINT `FK_AspNetUserRoles_AspNetUsers_UserId`
    FOREIGN KEY (`UserId`)
    REFERENCES `Nosted`.`AspNetUsers` (`Id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `Nosted`.`AspNetUserTokens`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Nosted`.`AspNetUserTokens` (
  `UserId` VARCHAR(255) NOT NULL,
  `LoginProvider` VARCHAR(255) NOT NULL,
  `Name` VARCHAR(255) NOT NULL,
  `Value` LONGTEXT NULL DEFAULT NULL,
  PRIMARY KEY (`UserId`, `LoginProvider`, `Name`),
  CONSTRAINT `FK_AspNetUserTokens_AspNetUsers_UserId`
    FOREIGN KEY (`UserId`)
    REFERENCES `Nosted`.`AspNetUsers` (`Id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `Nosted`.`Kunde`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Nosted`.`Kunde` (
  `Id` INT(11) NOT NULL AUTO_INCREMENT,
  `Navn` LONGTEXT NULL DEFAULT NULL,
  `Etternavn` LONGTEXT NULL DEFAULT NULL,
  `Email` LONGTEXT NULL DEFAULT NULL,
  `TelefonNr` LONGTEXT NULL DEFAULT NULL,
  `AdresseId` INT(11) NOT NULL,
  PRIMARY KEY (`Id`),
  INDEX `IX_Kunde_AdresseId` (`AdresseId` ASC) VISIBLE,
  CONSTRAINT `FK_Kunde_Adresse_AdresseId`
    FOREIGN KEY (`AdresseId`)
    REFERENCES `Nosted`.`Adresse` (`Id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `Nosted`.`Produkt`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Nosted`.`Produkt` (
  `Id` INT(11) NOT NULL AUTO_INCREMENT,
  `RegNr` LONGTEXT NULL DEFAULT NULL,
  `Model` LONGTEXT NULL DEFAULT NULL,
  `Type` LONGTEXT NULL DEFAULT NULL,
  `Garanti` LONGTEXT NOT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `Nosted`.`Ordre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Nosted`.`Ordre` (
  `Id` INT(11) NOT NULL AUTO_INCREMENT,
  `ServiceDato` DATETIME(6) NOT NULL,
  `ServiceRep` LONGTEXT NOT NULL,
  `KundeId` INT(11) NOT NULL,
  `ProduktId` INT(11) NOT NULL,
  PRIMARY KEY (`Id`),
  INDEX `IX_Ordre_KundeId` (`KundeId` ASC) VISIBLE,
  INDEX `IX_Ordre_ProduktId` (`ProduktId` ASC) VISIBLE,
  CONSTRAINT `FK_Ordre_Kunde_KundeId`
    FOREIGN KEY (`KundeId`)
    REFERENCES `Nosted`.`Kunde` (`Id`)
    ON DELETE CASCADE,
  CONSTRAINT `FK_Ordre_Produkt_ProduktId`
    FOREIGN KEY (`ProduktId`)
    REFERENCES `Nosted`.`Produkt` (`Id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `Nosted`.`ServiceSkjema`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Nosted`.`ServiceSkjema` (
  `Id` INT(11) NOT NULL AUTO_INCREMENT,
  `AvtaltKunde` LONGTEXT NULL DEFAULT NULL,
  `DelerBrukt` LONGTEXT NULL DEFAULT NULL,
  `DelerSkiftet` LONGTEXT NULL DEFAULT NULL,
  `RepBeskrivelse` LONGTEXT NULL DEFAULT NULL,
  `UtfortAv` LONGTEXT NULL DEFAULT NULL,
  `ArbeidsTimer` INT(11) NOT NULL,
  `OrdreId` INT(11) NOT NULL,
  PRIMARY KEY (`Id`),
  INDEX `IX_ServiceSkjema_OrdreId` (`OrdreId` ASC) VISIBLE,
  CONSTRAINT `FK_ServiceSkjema_Ordre_OrdreId`
    FOREIGN KEY (`OrdreId`)
    REFERENCES `Nosted`.`Ordre` (`Id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `Nosted`.`Sjekkliste`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Nosted`.`Sjekkliste` (
  `Id` INT(11) NOT NULL AUTO_INCREMENT,
  `TrykkSetting` FLOAT NULL DEFAULT NULL,
  `TrekKraft` FLOAT NULL DEFAULT NULL,
  `BremseKraft` FLOAT NULL DEFAULT NULL,
  `Resultat` LONGTEXT NULL DEFAULT NULL,
  `MechanicComment` LONGTEXT NULL DEFAULT NULL,
  `ClutchLameller` LONGTEXT NULL DEFAULT NULL,
  `BremserBP` LONGTEXT NULL DEFAULT NULL,
  `TrommelLager` LONGTEXT NULL DEFAULT NULL,
  `Kjedestrammer` LONGTEXT NULL DEFAULT NULL,
  `Wire` LONGTEXT NULL DEFAULT NULL,
  `PinionLager` LONGTEXT NULL DEFAULT NULL,
  `KjedehjulKile` LONGTEXT NULL DEFAULT NULL,
  `SylinderLekasje` LONGTEXT NULL DEFAULT NULL,
  `Slanger` LONGTEXT NULL DEFAULT NULL,
  `HydraulikkblokkTest` LONGTEXT NULL DEFAULT NULL,
  `OljeskifteTank` LONGTEXT NULL DEFAULT NULL,
  `OljeskifteGirboks` LONGTEXT NULL DEFAULT NULL,
  `RingsylinderTetninger` LONGTEXT NULL DEFAULT NULL,
  `BremsesylinderTetninger` LONGTEXT NULL DEFAULT NULL,
  `Ledningsnett` LONGTEXT NULL DEFAULT NULL,
  `Radio` LONGTEXT NULL DEFAULT NULL,
  `Knappekasse` LONGTEXT NULL DEFAULT NULL,
  `OrdreId` INT(11) NOT NULL,
  PRIMARY KEY (`Id`),
  INDEX `IX_Sjekkliste_OrdreId` (`OrdreId` ASC) VISIBLE,
  CONSTRAINT `FK_Sjekkliste_Ordre_OrdreId`
    FOREIGN KEY (`OrdreId`)
    REFERENCES `Nosted`.`Ordre` (`Id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `Nosted`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Nosted`.`Users` (
  `Id` INT(11) NOT NULL AUTO_INCREMENT,
  `Fornavn` LONGTEXT NULL DEFAULT NULL,
  `Etternavn` LONGTEXT NULL DEFAULT NULL,
  `Email` LONGTEXT NOT NULL,
`IsAdmin` TINYINT,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `Nosted`.`__EFMigrationsHistory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Nosted`.`__EFMigrationsHistory` (
  `MigrationId` VARCHAR(150) NOT NULL,
  `ProductVersion` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`MigrationId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
