-- MySQL Script generated by MySQL Workbench
-- Thu Oct  5 15:44:16 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Nosted
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Nosted
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Nosted` DEFAULT CHARACTER SET utf8 ;
USE `Nosted` ;

-- -----------------------------------------------------
-- Table `Nosted`.`Adresse`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Nosted`.`Adresse` (
  `idAdresse` INT NOT NULL AUTO_INCREMENT,
  `adresse` VARCHAR(45) NOT NULL,
  `postKode` INT NOT NULL,
  PRIMARY KEY (`idAdresse`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Nosted`.`Kunde`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Nosted`.`Kunde` (
  `idKunde` INT NOT NULL AUTO_INCREMENT,
  `Fornavn` VARCHAR(45) NOT NULL,
  `Etternavn` VARCHAR(45) NOT NULL,
  `TelefonNr` VARCHAR(20) NOT NULL,
  `Email` VARCHAR(45) NULL,
  `Adresse_idAdresse` INT NOT NULL,
  PRIMARY KEY (`idKunde`),
  INDEX `fk_Kunde_Adresse1_idx` (`Adresse_idAdresse` ASC) VISIBLE,
  CONSTRAINT `fk_Kunde_Adresse1`
    FOREIGN KEY (`Adresse_idAdresse`)
    REFERENCES `Nosted`.`Adresse` (`idAdresse`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Nosted`.`ServiceSkejma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Nosted`.`ServiceSkejma` (
  `idServiceSkejma` INT NOT NULL AUTO_INCREMENT,
  `kundeKommentar` TEXT NOT NULL,
  `repBeskrivelse` TEXT NOT NULL,
  `arbeidsTimer` INT NOT NULL,
  PRIMARY KEY (`idServiceSkejma`) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Nosted`.`Vinsj`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Nosted`.`Vinsj` (
  `idVinsj` INT NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(45) NOT NULL,
  `model` VARCHAR(45) NOT NULL,
  `registreringsNr` VARCHAR(45) NOT NULL,
  `Kunde_idKunde` INT NOT NULL,
  PRIMARY KEY (`idVinsj`),
  INDEX `fk_Vinsj_Kunde1_idx` (`Kunde_idKunde` ASC) VISIBLE,
  CONSTRAINT `fk_Vinsj_Kunde1`
    FOREIGN KEY (`Kunde_idKunde`)
    REFERENCES `Nosted`.`Kunde` (`idKunde`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Nosted`.`Sjekkliste`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Nosted`.`Sjekkliste` (
  `idSjekkliste` INT NOT NULL AUTO_INCREMENT,
  `mechanicComment` TEXT NOT NULL,
  `trykkBar` DECIMAL NOT NULL,
  `bremseKraft` DECIMAL NOT NULL,
  `rekkraft` DECIMAL NOT NULL,
  `vinsjTestet` TINYINT NULL,
  PRIMARY KEY (`idSjekkliste`) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Nosted`.`Sjekk`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Nosted`.`Sjekk` (
  `idSjekk` INT NOT NULL AUTO_INCREMENT,
  `sjekkNavn` VARCHAR(45) NOT NULL,
  `sjekkStatus` VARCHAR(45) NOT NULL,
  `Sjekkliste_idSjekkliste` INT NOT NULL,
  PRIMARY KEY (`idSjekk`),
  INDEX `fk_Sjekk_Sjekkliste1_idx` (`Sjekkliste_idSjekkliste` ASC) VISIBLE,
  CONSTRAINT `fk_Sjekk_Sjekkliste1`
    FOREIGN KEY (`Sjekkliste_idSjekkliste`)
    REFERENCES `Nosted`.`Sjekkliste` (`idSjekkliste`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Nosted`.`Ordre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Nosted`.`Ordre` (
  `idOrdre` INT NOT NULL AUTO_INCREMENT,
  `fullført` TINYINT NULL,
  `opprettetDato` DATETIME NOT NULL,
  `Kunde_idKunde` INT NOT NULL,
  `ServiceSkejma_idServiceSkejma` INT NOT NULL,
  `Sjekkliste_idSjekkliste` INT NOT NULL,
  PRIMARY KEY (`idOrdre`),
  INDEX `fk_Ordre_Kunde1_idx` (`Kunde_idKunde` ASC) VISIBLE,
  INDEX `fk_Ordre_ServiceSkejma1_idx` (`ServiceSkejma_idServiceSkejma` ASC) VISIBLE,
  INDEX `fk_Ordre_Sjekkliste1_idx` (`Sjekkliste_idSjekkliste` ASC) VISIBLE,
  CONSTRAINT `fk_Ordre_Kunde1`
    FOREIGN KEY (`Kunde_idKunde`)
    REFERENCES `Nosted`.`Kunde` (`idKunde`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ordre_ServiceSkejma1`
    FOREIGN KEY (`ServiceSkejma_idServiceSkejma`)
    REFERENCES `Nosted`.`ServiceSkejma` (`idServiceSkejma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ordre_Sjekkliste1`
    FOREIGN KEY (`Sjekkliste_idSjekkliste`)
    REFERENCES `Nosted`.`Sjekkliste` (`idSjekkliste`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `Nosted`.`Ansatt`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Nosted`.`Ansatt` (
  `idAnsatt` INT NOT NULL AUTO_INCREMENT,
  `fornavn` VARCHAR(45) NOT NULL,
  `etternavn` VARCHAR(45) NOT NULL,
  `stilling` VARCHAR(45) NOT NULL,
  `Adresse_idAdresse` INT NOT NULL,
  PRIMARY KEY (`idAnsatt`),
  INDEX `fk_Ansatt_Adresse1_idx` (`Adresse_idAdresse` ASC) VISIBLE,
  CONSTRAINT `fk_Ansatt_Adresse1`
    FOREIGN KEY (`Adresse_idAdresse`)
    REFERENCES `Nosted`.`Adresse` (`idAdresse`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Nosted`.`Del`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Nosted`.`Del` (
  `idDel` INT NOT NULL,
  `delNavn` VARCHAR(45) NOT NULL,
  `ServiceSkejma_idServiceSkejma` INT NOT NULL,
  PRIMARY KEY (`idDel`),
  INDEX `fk_Del_ServiceSkejma1_idx` (`ServiceSkejma_idServiceSkejma` ASC) VISIBLE,
  CONSTRAINT `fk_Del_ServiceSkejma1`
    FOREIGN KEY (`ServiceSkejma_idServiceSkejma`)
    REFERENCES `Nosted`.`ServiceSkejma` (`idServiceSkejma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
